# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(default='2', max_length=50, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='1.com', max_length=254, verbose_name='邮箱'),
        ),
    ]
