# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20170705_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=50, verbose_name='住址'),
        ),
    ]
