# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20170705_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
