# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_remove_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hrm.Department', verbose_name='部门'),
        ),
    ]
