# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工信息表', 'verbose_name_plural': '员工信息表'},
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='验证时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=20, verbose_name='验证码类型'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], max_length=10, verbose_name='性别'),
        ),
    ]
