# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_remove_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.ImageField(default=0, upload_to='', verbose_name='薪资'),
            preserve_default=False,
        ),
    ]
