# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lateCount', models.IntegerField(verbose_name='迟到次数')),
                ('absenceCount', models.IntegerField(verbose_name='旷工次数')),
                ('leaveCount', models.IntegerField(verbose_name='早退次数')),
                ('comment', models.CharField(max_length=50, verbose_name='评论')),
            ],
            options={
                'verbose_name': '员工考勤管理',
                'verbose_name_plural': '员工考勤管理',
                'db_table': 'sttendance_message',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息管理', 'verbose_name_plural': '部门信息管理'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工信息管理', 'verbose_name_plural': '员工信息管理'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='1@qq..com', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.Staff', verbose_name='员工'),
        ),
    ]
