# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0017_auto_20181113_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='gradSchool',
            field=models.CharField(default='', max_length=20, verbose_name='毕业学校'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='11111111111@qq..com', max_length=254, verbose_name='邮箱'),
        ),
    ]
