# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_auto_20181116_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary_num',
            field=models.IntegerField(default=0, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='11111111111@qq.com', max_length=254, verbose_name='邮箱'),
        ),
    ]
