# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_auto_20181116_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='workOvertime',
            field=models.IntegerField(default=0, verbose_name='加班时间'),
        ),
        migrations.AddField(
            model_name='salary',
            name='delWages',
            field=models.IntegerField(default=0, verbose_name='扣除工资'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absenceCount',
            field=models.IntegerField(default=0, verbose_name='旷工次数'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lateCount',
            field=models.IntegerField(default=0, verbose_name='迟到次数'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leaveCount',
            field=models.IntegerField(default=0, verbose_name='早退次数'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.FloatField(default=0, verbose_name='本月薪资'),
        ),
    ]
